export const FLAVOURS = [
  {
    id: 'original',
    name: 'Original',
    image: '/images/can-range-original.png',
    productImage: '/images/redesign/product-card-original.webp',
    accent: '#fafaf5',
    accentB: '#c8d4f0',
    badge: 'Hero',
    description: 'Cold, lightly sparkling sato brewed from Thai sticky rice.',
  },
  {
    id: 'lime',
    name: 'Lime',
    image: '/images/can-range-lime.png',
    productImage: '/images/redesign/product-card-lime.webp',
    accent: '#9fd8a8',
    accentB: '#fafaf5',
    badge: 'Citrus',
    description: 'Bright citrus lift — best with ice and a lime slice.',
  },
  {
    id: 'cantaloupe',
    name: 'Cantaloupe',
    image: '/images/can-range-cantaloupe.png',
    productImage: '/images/redesign/product-card-cantaloupe.webp',
    accent: '#f0c888',
    accentB: '#fafaf5',
    badge: 'Fruit',
    description: 'Soft melon sweetness for long Thai table meals.',
  },
  {
    id: 'krajiab',
    name: 'Krajiab',
    image: '/images/can-range-krajiab.png',
    productImage: '/images/redesign/product-card-krajiab.webp',
    accent: '#fafaf5',
    accentB: '#9fd8a8',
    badge: 'Floral',
    description: 'Floral roselle notes — a modern Thai table discovery.',
  },
];
